/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".nav[_ngcontent-%COMP%]{\r\n    \r\n    background-color:#e0dbdb;\r\n    \r\n    \r\n    \r\n  }\r\n  li[_ngcontent-%COMP%]{\r\n    padding:10px;\r\n  }\r\n  \r\n  .active[_ngcontent-%COMP%]{\r\n    background-color:#8a8989;\r\n  }\r\n  \r\n  a[_ngcontent-%COMP%]{\r\n    color: #202020;\r\n  \r\n  }\r\n  \r\n  a[_ngcontent-%COMP%]:hover{\r\n    color:#000000;\r\n  }"];
export { styles as styles };
//# sourceMappingURL=navbar.component.css.shim.ngstyle.js.map