/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["img[_ngcontent-%COMP%] {\r\n    border-radius: 50%;\r\n    width: 90px;\r\n  }\r\n\r\n  li[_ngcontent-%COMP%]{\r\n      list-style: none;\r\n      \r\n      \r\n  }\r\n\r\n  span[_ngcontent-%COMP%]{\r\n      font-size: large;\r\n      font-weight: bold;\r\n      top:-50px;\r\n      left:5px;\r\n      position: relative;\r\n      \r\n  }\r\n\r\n  a[_ngcontent-%COMP%]{\r\n  height: 20px;\r\n     \r\n     \r\n      text-decoration: none; \r\n       \r\n      \r\n     \r\n  }"];
export { styles as styles };
//# sourceMappingURL=github-followers.component.css.shim.ngstyle.js.map